### ISSUE TITLE
Error: cannot load such file -- EGP_Rates (LoadError)

### ISSUE THREAD

**Issue by drdrsh** [mad-raz/EGP-Rates-CLI#1]
This is the stack trace of the error

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- EGP_Rates (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/EGP_Rates_CLI-0.0.1/lib/EGP_Rates_CLI.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/EGP_Rates_CLI-0.0.1/bin/egp:4:in `<top (required)>'
	from /usr/local/bin/egp:23:in `load'

I don't know Ruby so I am not sure what I needed  to do but I already installed EGP_Rates using
`gem install EGP_Rates`
and then ran
`gem install EGP_Rates_CLI`

No errors encountered until I run egp where I get that error.

I am running this on Ubuntu 16.04

**Comment by a14m** [comment]
BTW, you can ignore `gem install EGP_Rates` it should be automatically bundled (installed within) the `gem install EGP_Rates_CLI` command... 
will work on that fix and publish it (since I could reproduce the issue)

**Comment by a14m** [comment]
should be fixed now... please run `gem install EGP_Rates_CLI` to update
and please don't hesitate to report any other issue you find 😉
