### ISSUE TITLE
Cannot load such file (Load Error)

### ISSUE THREAD

**Issue by muhammednagy** [mad-raz/EGP-Rates-CLI#2]
Hello i tried to use the CLI but i have got Cannot load such file error 
i'm working on it

**Comment by a14m** [comment]
can you put the logs of the error here with the system specifications ? (like ruby version, how you installed it) ?

**Comment by muhammednagy** [comment]
here u are
$ uname -a
Linux muhammednagy 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
i am using rvm 
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
i installed it using terminal 
gem install EGP_Rates_CLI

trying egp :
$ egp
/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- egp_rates_cli (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/EGP_Rates_CLI-1.0.0/bin/egp:4:in `<top (required)>'
	from /usr/local/bin/egp:23:in `load'
	from /usr/local/bin/egp:23:in `<main>'

i tried my edits on 2 different machines and it worked !!

**Comment by a14m** [comment]
try `gem uninstall EGP_Rates_CLI` and then install again and see if it works?
I really don't know why it failed because I'm using it and I know some people are using it (and they didn't have this problem)

**Comment by a14m** [comment]
I merged the changes and updated the gem... just use `gem update EGP_Rates_CLI` and it should update to the latest version (`1.0.1`)

**Comment by muhammednagy** [comment]
thanks 
o tried to uninstall it and reinstall it multiple times before you merged my pull request and it didn't work
